dev:
	deno run --allow-net --allow-hrtime --allow-env --allow-read --watch main.ts
build:
	deno run --allow-read --allow-hrtime --allow-write --allow-net --allow-run --allow-env build.ts 
lint:
	deno lint main.ts
test:
	deno test main.ts